apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dqtiafa00-nodejs 
  janus-idp.io/tekton: dqtiafa00-nodejs
  backstage.io/kubernetes-id: dqtiafa00-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dqtiafa00-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml